### ISSUE TITLE
Main menu and Add new patient

### ISSUE THREAD

**Issue by Abdulwahaab710** [Della-crop/client-mobile-app#1]
- The window should contain 
     - 4 textboxes
     - 1 button
Check photo below 

| Main menu | Add new patient UI |
| ----------- | ------------------- |
| ![screen shot 2017-03-09 at 12 58 28 pm](https://cloud.githubusercontent.com/assets/13983801/23826970/7938b59c-0676-11e7-921e-5ce062c5761f.png) | ![screen shot 2017-03-11 at 4 12 44 pm](https://cloud.githubusercontent.com/assets/13983801/23826939/f8750e06-0675-11e7-8fce-715751e36818.png) |

### Task:
- Design the UI
- [You should be able to send a post request to server with data for the Add new patient form](https://facebook.github.io/react-native/docs/network.html)

### Additional resources:
https://medium.com/@yoniweisbrod/interacting-with-apis-using-react-native-fetch-9733f28566bb#.ob6vsejfm

**Comment by RickyLiu95** [comment]
[GNG2101 mobile app.zip](https://github.com/Della-crop/client-mobile-app/files/874430/GNG2101.mobile.app.zip)
