### ISSUE TITLE
Update the patient info

### ISSUE THREAD

**Issue by Abdulwahaab710** [Della-crop/client-mobile-app#2]
- The window should contain 
     - Search for a patient
          - 1 textbox
     - Update
          - 4 textboxes
          - 1 button
Check photo below 

| Search for a patient UI | Update info form |
| ----------- | ------------------- |
| ![screen shot 2017-03-11 at 4 42 59 pm](https://cloud.githubusercontent.com/assets/13983801/23827106/e40ebde6-0679-11e7-896c-a56b9d26157b.png) | ![screen shot 2017-03-11 at 4 43 08 pm](https://cloud.githubusercontent.com/assets/13983801/23827104/dfd908ee-0679-11e7-9731-5c921b56d2b7.png) |
### Task:
- Design the UI
- [load the existing data to the form](https://facebook.github.io/react-native/docs/network.html)
- [You should be able to send a post request with the changed data to server](https://facebook.github.io/react-native/docs/network.html)

### Additional resources:
https://medium.com/@yoniweisbrod/interacting-with-apis-using-react-native-fetch-9733f28566bb#.ob6vsejfm

---
```js
import {
    Dimensions,
    Image,
    ListView,
    Modal,
    ScrollView,
    StyleSheet,
    Text,
    TextInput,
    TouchableOpacity,
    View,
} from 'react-native';
```
https://github.com/abdulwahaab710/picme

Send HTTP POST to the server, then the server will return a JSON response.

**Comment by XCMF-007** [comment]
I will assign this one to myself
