### ISSUE TITLE
implement the push notification

### ISSUE THREAD

**Issue by Abdulwahaab710** [Della-crop/client-mobile-app#3]
- The window should Alert the nurse when a patient falls
Check photo below 

| Alert screen |
| ----------- |
| ![screen shot 2017-03-11 at 4 13 06 pm](https://cloud.githubusercontent.com/assets/13983801/23827169/2a74c194-067b-11e7-9b97-a1ab5708b2fd.png) |

### Task:
- Implement the push notification in the backend
- Trigger the alert screen via push notification
- Design UI
- Design database for patient info and logs

**Comment by RickyLiu95** [comment]
hey Abdul, could you give me any tutorial links to help me finish this part?

**Comment by Abdulwahaab710** [comment]
Hey @RickyLiu95,

This is the hardest part in the whole project.
Check the other issue.
